name: ksrce_erp
description: KSRCE ERP - Enterprise Resource Planning System for K.S.R. College of Engineering

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & Navigation
  go_router: ^13.2.0
  provider: ^6.1.0
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  
  # Utilities
  intl: ^0.19.0
  clipboard: ^0.1.3
  
  # UI/UX
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
